AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Template IAM_Users_Groups_and_Policies: 
  Template to create IAM users, groups and policies. It creates a single
  user that is a member of a users group. The groups each have
  different IAM policies associated with them. Note: This template creates an
  AWSAccessKeyId/AWSSecretKey pair associated with the new user.'
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '12'
    MaxLength: '41'
    ConstraintDescription: the password must be between 12 and 41 characters
Resources:
  ECRUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'Password'
  ECRUserGroup:
    Type: AWS::IAM::Group
  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'ECRUserGroup'
      Users: [!Ref 'ECRUser']
  ECRUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECRUsers
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['ecr:DescribeImages', 'ecr:DescribeRepositories']
          Resource: '*'
      Groups: [!Ref 'ECRUserGroup']
  ECRKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'ECRUser'
Outputs:
  AccessKey:
    Value: !Ref 'ECRKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [ECRKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
